// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkPinnedUsingNoteIDandUserID = `-- name: CheckPinnedUsingNoteIDandUserID :one
SELECT is_pinned FROM notes 
WHERE user_id = $1 AND id = $2
`

type CheckPinnedUsingNoteIDandUserIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) CheckPinnedUsingNoteIDandUserID(ctx context.Context, arg CheckPinnedUsingNoteIDandUserIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkPinnedUsingNoteIDandUserID, arg.UserID, arg.ID)
	var is_pinned bool
	err := row.Scan(&is_pinned)
	return is_pinned, err
}

const countPinnedNotes = `-- name: CountPinnedNotes :one
SELECT COUNT(*) FROM notes
WHERE user_id = $1 AND is_pinned = TRUE
`

func (q *Queries) CountPinnedNotes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPinnedNotes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (id, created_at, updated_at, title, body, user_id, is_pinned)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1, 
    $2,
    $3,
    $4
) RETURNING id, created_at, updated_at, body, user_id, title, is_pinned
`

type CreateNoteParams struct {
	Title    string
	Body     string
	UserID   uuid.UUID
	IsPinned bool
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.Title,
		arg.Body,
		arg.UserID,
		arg.IsPinned,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.Title,
		&i.IsPinned,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, created_at, updated_at, body, user_id, title, is_pinned FROM notes
WHERE id = $1
`

func (q *Queries) GetNoteByID(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.Title,
		&i.IsPinned,
	)
	return i, err
}

const getNotesByUserID = `-- name: GetNotesByUserID :many
SELECT id, created_at, updated_at, body, user_id, title, is_pinned FROM notes
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetNotesByUserID(ctx context.Context, userID uuid.UUID) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
			&i.Title,
			&i.IsPinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET
  title = COALESCE($1, title),
  body = COALESCE($2, body),
  is_pinned = COALESCE($3, is_pinned),
  updated_at = NOW()
WHERE id = $4 AND user_id = $5
RETURNING id, created_at, updated_at, body, user_id, title, is_pinned
`

type UpdateNoteParams struct {
	Title    sql.NullString
	Body     sql.NullString
	IsPinned sql.NullBool
	ID       uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.Title,
		arg.Body,
		arg.IsPinned,
		arg.ID,
		arg.UserID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.Title,
		&i.IsPinned,
	)
	return i, err
}
