// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (id, created_at, updated_at, title ,body, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1, 
    $2,
    $3
) RETURNING id, created_at, updated_at, body, user_id, title
`

type CreateNoteParams struct {
	Title  string
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.Title, arg.Body, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.Title,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, created_at, updated_at, body, user_id, title FROM notes
WHERE id = $1
`

func (q *Queries) GetNoteByID(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.Title,
	)
	return i, err
}

const getNotesByUserID = `-- name: GetNotesByUserID :many
SELECT id, created_at, updated_at, body, user_id, title FROM notes
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetNotesByUserID(ctx context.Context, userID uuid.UUID) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET
  title = COALESCE($1, title),
  body = COALESCE($2, body),
  updated_at = NOW()
WHERE id = $3 AND user_id = $4
RETURNING id, created_at, updated_at, body, user_id, title
`

type UpdateNoteParams struct {
	Title  sql.NullString
	Body   sql.NullString
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.Title,
		arg.Body,
		arg.ID,
		arg.UserID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
		&i.Title,
	)
	return i, err
}
